# Generated by Django 3.1.6 on 2021-04-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_studentblock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentblock',
            old_name='studentname',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='studentblock',
            name='studentemail',
        ),
        migrations.RemoveField(
            model_name='studentblock',
            name='studentmobile',
        ),
        migrations.AddField(
            model_name='studentblock',
            name='dob',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentblock',
            name='last_name',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentblock',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
